name: Newman run

on: 
  workflow_dispatch: # Permite execução manual via interface do GitHub Actions

jobs:
  newman:
    runs-on: ubuntu-latest
    steps:
      # Checkout do repositório para acessar os arquivos
      - name: Checkout code
        uses: actions/checkout@v3

      # Criação de diretório para os relatórios
      - name: Create dir for report
        run: mkdir -p testArtifacts

      # Instalação do Newman e do HTML Extra Reporter
      - name: Install Newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      # Execução dos testes com o Newman
      - name: Run Test
        run: |
          newman run ServeRest.postman_collection.json \
          -e serveRest_env.postman_environment.json \
          -r htmlextra --reporter-htmlextra-export testArtifacts/report.html

      # Upload do relatório gerado
      - name: Upload Report
        uses: actions/upload-artifact@v3.1.2
        with:
          name: Newman Report
          path: testArtifacts/report.html
